### ISSUE TITLE
[BUG] Installing packages is broken on Arch and Arch-based distributions

### ISSUE THREAD

**Issue by macbian-linux** [eupnea-linux/eupnea-builder#24]
**Describe the bug**
When attempting to create the image using the official instructions found on the wiki, I get an error relating to makepkg and sudo. The screenshot and log should include all required information.

**To Reproduce**
1. Run ``git clone --depth=1 https://github.com/eupnea-linux/eupnea-builder; cd eupnea-builder; ./main.py``
2. Select anything as distro
3. Select anything as desktop environment

**Screenshots**
![image](https://user-images.githubusercontent.com/104112636/193435063-13c3dbff-40ff-4589-93b0-a25716f5bc6a.png)

**Build system (please complete the following information):**
 - OS: The latest versions of Arch and Manjaro both have the same issue.

==FULL LOG:
**Additional context**

== FULL LOG ==
Welcome to Eupnea
This script will create a bootable Eupnea USB-drive/SD-card/image for you.
You will now be asked a few questions. If you dont know what to answer, just press 'enter' and the recommended answer will be used.
(Press enter to continue)
Which Linux distro(flavor) would you like to use?
Available options: Ubuntu(default, recommended), Debian, Arch, Fedora

Use latest Ubuntu version?
Press enter for yes, or type in the version number(example: '21.10'): 22.04
Ubuntu: 22.04 selected
Which desktop environment(Desktop GUI) would you like to use?
Available options: Gnome(default, recommended), KDE(recommended), MATE, Xfce(recommended for weak devices), LXQt(recommended for weak devices), deepin, budgie, cli
KDE
KDE selected
Enter username to be used in Eupnea
Username(default: 'localuser'): 
Using 'localuser' as username
Please set a secure password
Password: 
Repeat password: 
Password set
Enter hostname for the chromebook.(Hostname is something like a device name)
Hostname(default: 'eupnea-chromebook'): 
Using eupnea-chromebook as hostname
Would you like to rebind the Search/Super/Win key to Caps Lock?(NOT RECOMMENDED)
Type yes to rebind. Press enter to keep old binding: 
Search key will be Super/Win key
No available USBs/SD-cards found. Building image file.
User input complete
Starting build
Preparing host system
Failed to unmount /tmp/eupnea-build/fedora-tmp-mnt, ignore
Cleaning + preparing host system
Installing: vboot, cgpt, parted
Failed to remove /tmp/eupnea-packages/cgpt-bin with python, using bash
Failed to remove /tmp/eupnea-packages/vboot-utils with python, using bash
warning: archlinux-keyring-20220831-1 is up to date -- skipping
warning: autoconf-2.71-1 is up to date -- skipping
warning: automake-1.16.5-1 is up to date -- skipping
warning: binutils-2.39-3 is up to date -- skipping
warning: bison-3.8.2-4 is up to date -- skipping
warning: fakeroot-1.29-1 is up to date -- skipping
warning: file-5.42-2 is up to date -- skipping
warning: findutils-4.9.0-1 is up to date -- skipping
warning: flex-2.6.4-3 is up to date -- skipping
warning: gawk-5.1.1-1 is up to date -- skipping
warning: gcc-12.2.0-1 is up to date -- skipping
warning: gettext-0.21-2 is up to date -- skipping
warning: grep-3.7-1 is up to date -- skipping
warning: groff-1.22.4-7 is up to date -- skipping
warning: gzip-1.12-1 is up to date -- skipping
warning: libtool-2.4.7-5 is up to date -- skipping
warning: m4-1.4.19-1 is up to date -- skipping
warning: make-4.3-3 is up to date -- skipping
warning: manjaro-keyring-20220514-2 is up to date -- skipping
warning: pacman-6.0.1-12 is up to date -- skipping
warning: patch-2.7.6-8 is up to date -- skipping
warning: pkgconf-1.8.0-1 is up to date -- skipping
warning: sed-4.8-1 is up to date -- skipping
warning: sudo-1.9.11.p3-1 is up to date -- skipping
warning: texinfo-6.8-2 is up to date -- skipping
warning: which-2.21-5 is up to date -- skipping
Cloning into '/tmp/eupnea-packages/cgpt-bin'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 4 (delta 0), pack-reused 0
Receiving objects: 100% (4/4), done.
Cloning into '/tmp/eupnea-packages/vboot-utils'...
remote: Enumerating objects: 98, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 98 (delta 12), reused 97 (delta 12), pack-reused 0
Receiving objects: 100% (98/98), 24.31 KiB | 24.31 MiB/s, done.
Resolving deltas: 100% (12/12), done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30112  100 30112    0     0  80962      0 --:--:-- --:--:-- --:--:-- 80946
    cgpt.deb ... Passed
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
==> WARNING: Failed to install built package(s).
Traceback (most recent call last):
  File "/home/distrohopper39b/eupnea-builder/./main.py", line 107, in <module>
    build = build.start_build(args.verbose, local_path=args.local_path, kernel_type=kernel_type,
  File "/home/distrohopper39b/eupnea-builder/build.py", line 443, in start_build
    prepare_host(build_options["distro_name"], user_id)
  File "/home/distrohopper39b/eupnea-builder/build.py", line 25, in prepare_host
    install_build_packages(user_id)
  File "/home/distrohopper39b/eupnea-builder/functions.py", line 160, in install_build_packages
    bash(f'su -c "cd /tmp/eupnea-packages/cgpt-bin && makepkg -sirc --noconfirm" {user_id}')
  File "/home/distrohopper39b/eupnea-builder/functions.py", line 115, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'su -c "cd /tmp/eupnea-packages/cgpt-bin && makepkg -sirc --noconfirm" distrohopper39b' returned non-zero exit status 14.

**Comment by Apacelus** [comment]
Unfortunately the project doesnt have a lot of active testers, so it seems this is one of those issues that didnt get caught. (Then again, Eupnea is currently in testing with v1.0 coming soon) 
I will fix this issue in a day or two

**Comment by macbian-linux** [comment]
Thanks! If you need any help with testing feel free to let me know! My discord is DistroHopper39B#5793 and I just joined your server.

**Comment by Apacelus** [comment]
Fixed in https://github.com/Apacelus/python-os-functions/commit/f4d8acacf4ea08e562d2451142af4dffb1e66fa3 and subsequently https://github.com/eupnea-linux/eupnea-builder/commit/bd9b794c3f61a011e7486520892fbdff0029bfa3
