### ISSUE TITLE
[BUG] Default hostname eupnea_chromebook breaks sudo. 

### ISSUE THREAD

**Issue by BigBoiMan123** [eupnea-linux/eupnea-builder#26]
**Describe the bug**
The default hostname for the disk image is eupnea_chromebook, which contains an underscore. This breaks sudo with the error: unable to resolve hostname. Because sudo is broken and there is no option to enable the root account, you can't edit /etc/hostname; the system is soft bricked. The .img is also written like a CD onto a USB Drive, so you cannot manually edit the files on another OS. 

**To Reproduce**
1. Run ``git clone --depth=1 https://github.com/eupnea-linux/eupnea-builder; cd eupnea-builder; ./main.py``
2. Select Ubuntu
3. Select KDE as desktop environment
4. Flash the .img to a USB drive using Rufus
5. Boot from the USB
6. Try to use sudo

**Build system (please complete the following information):**
 - OS: WSL 2 on Windows 11

**Comment by Apacelus** [comment]
Does this get resolved when there is no underscore in the hostname?

**Comment by Apacelus** [comment]
Can you please rebuild? I have solved this issue a few days ago already

**Comment by Apacelus** [comment]
Shouldve been fixed as part of https://github.com/eupnea-linux/eupnea-builder/commit/3be1913ba966912a0b4367699148338fb53d5347

**Comment by BigBoiMan123** [comment]
Rebuilt the ISO and it works now, the problem is I cloned the repo a few days before I actually built the ISO, but forgot to run git pull.
